apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/deverathore/helm-charts.git
    targetRevision: HEAD
    path: charts/python-api
    helm:
      values: |
        image:
          repository: deverathore13/python-api
          tag: latest
        replicas: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        ingress:
          enabled: true
          host: api.example.com
  
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
